version: '3'

services:
  nest-api:
    image: nest-dev/api:latest
    container_name: nest-api
    tty: true
    command:
      - /entrypoint.sh
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    networks:
      - nest-network

  nest-db:
    image: mysql:5.7
    container_name: nest-db
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --init-file /data/application/init.sql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./_Docker/mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - nest-network

  nest-migrations:
    image: nest-dev/migrations:latest
    container_name: nest-migrations
    tty: true
    command:
      - /entrypoint.sh
    volumes:
      - ./migrations:/app
    networks:
      - nest-network
    depends_on:
      - nest-db

networks:
  nest-network:
    driver: bridge
